# PostInstallInjector.ps1
# Injects post-install scripts into the Windows image that run after first boot

function Add-PostInstallScript {
    <#
    .SYNOPSIS
        Injects a SetupComplete.cmd script that runs after Windows installation completes.
    .PARAMETER MountPath
        Path to the mounted Windows image.
    .PARAMETER DestinationPath
        Path to the ISO working directory.
    .PARAMETER Commands
        Array of commands to run post-install.
    .PARAMETER ScriptPath
        Path to an existing script file to inject (alternative to Commands).
    #>
    param(
        [Parameter(Mandatory=$true)][string]$MountPath,
        [Parameter(Mandatory=$true)][string]$DestinationPath,
        [string[]]$Commands = @(),
        [string]$ScriptPath = ""
    )

    Write-Host "`n[INFO] Injecting post-install scripts..." -ForegroundColor Cyan
    Write-Log -msg "Injecting post-install scripts"

    # SetupComplete.cmd runs after OOBE with SYSTEM privileges
    $setupCompletePath = Join-Path $MountPath "Windows\Setup\Scripts"
    $setupCompleteFile = Join-Path $setupCompletePath "SetupComplete.cmd"

    # Create Scripts directory if it doesn't exist
    if (-not (Test-Path $setupCompletePath)) {
        New-Item -ItemType Directory -Path $setupCompletePath -Force | Out-Null
        Write-Log -msg "Created Scripts directory: $setupCompletePath"
    }

    # Build the script content
    $scriptContent = @()
    $scriptContent += "@echo off"
    $scriptContent += ":: Windows ISO Debloater - Post-Install Script"
    $scriptContent += ":: This script runs automatically after Windows installation"
    $scriptContent += ":: Running as SYSTEM account"
    $scriptContent += ""
    $scriptContent += "echo [%date% %time%] Post-install script started >> C:\Windows\Setup\Scripts\postinstall.log"
    $scriptContent += ""

    if ($ScriptPath -and (Test-Path $ScriptPath)) {
        # Inject content from external script file
        $externalContent = Get-Content $ScriptPath
        $scriptContent += $externalContent
        Write-Log -msg "Injected external script: $ScriptPath"
    }

    if ($Commands.Count -gt 0) {
        $scriptContent += ":: Custom commands"
        foreach ($cmd in $Commands) {
            $scriptContent += $cmd
        }
    }

    # Always add default post-install optimizations
    $scriptContent += ""
    $scriptContent += ":: Clean up temporary files"
    $scriptContent += "del /q /f C:\Windows\Temp\* 2>nul"
    $scriptContent += "del /q /f %TEMP%\* 2>nul"
    $scriptContent += ""
    $scriptContent += "echo [%date% %time%] Post-install script completed >> C:\Windows\Setup\Scripts\postinstall.log"

    # Write the script
    $scriptContent | Out-File -FilePath $setupCompleteFile -Encoding ASCII -Force
    Write-Log -msg "SetupComplete.cmd written to: $setupCompleteFile"

    Write-Host "[OK] Post-install script injected" -ForegroundColor Green
    Write-Log -msg "Post-install script injection completed"
}

function Add-FirstBootPowerShellScript {
    <#
    .SYNOPSIS
        Injects a PowerShell script that runs on first user logon.
    .PARAMETER MountPath
        Path to the mounted Windows image.
    .PARAMETER ScriptContent
        PowerShell script content as string array.
    .PARAMETER ScriptName
        Name for the script file.
    #>
    param(
        [Parameter(Mandatory=$true)][string]$MountPath,
        [Parameter(Mandatory=$true)][AllowEmptyString()][string[]]$ScriptContent,
        [string]$ScriptName = "FirstBoot.ps1"
    )

    $scriptsPath = Join-Path $MountPath "Windows\Setup\Scripts"
    $psScriptPath = Join-Path $scriptsPath $ScriptName

    if (-not (Test-Path $scriptsPath)) {
        New-Item -ItemType Directory -Path $scriptsPath -Force | Out-Null
    }

    $ScriptContent | Out-File -FilePath $psScriptPath -Encoding UTF8 -Force

    # Add to RunOnce to execute on first logon
    reg add "HKLM\zSOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce" /v "FirstBootScript" /t REG_SZ /d "powershell -ExecutionPolicy Bypass -File C:\Windows\Setup\Scripts\$ScriptName" /f 2>&1 | Write-Log

    Write-Log -msg "First-boot PowerShell script injected: $ScriptName"
}

function Add-WinGetInstallScript {
    <#
    .SYNOPSIS
        Creates a post-install script that installs apps via WinGet on first boot.
    .PARAMETER MountPath
        Path to the mounted Windows image.
    .PARAMETER Apps
        Array of WinGet app IDs to install.
    #>
    param(
        [Parameter(Mandatory=$true)][string]$MountPath,
        [string[]]$Apps = @()
    )

    if ($Apps.Count -eq 0) { return }

    Write-Host "  Adding WinGet auto-install for $($Apps.Count) apps..." -ForegroundColor DarkGray

    $psContent = @()
    $psContent += "# WinGet Auto-Install Script - Generated by Windows ISO Debloater"
    $psContent += "# Waits for internet and installs specified apps"
    $psContent += ""
    $psContent += "Start-Sleep -Seconds 30  # Wait for network"
    $psContent += ""
    $psContent += '# Wait for internet connection'
    $psContent += 'while (-not (Test-Connection 8.8.8.8 -Count 1 -Quiet -ErrorAction SilentlyContinue)) {'
    $psContent += '    Start-Sleep -Seconds 10'
    $psContent += '}'
    $psContent += ""
    $psContent += '# Install apps via WinGet'
    $psContent += '$apps = @('
    foreach ($app in $Apps) {
        $psContent += "    `"$app`","
    }
    $psContent += ')'
    $psContent += ''
    $psContent += 'foreach ($app in $apps) {'
    $psContent += '    Write-Host "Installing $app..."'
    $psContent += '    winget install --id $app --accept-source-agreements --accept-package-agreements --silent 2>$null'
    $psContent += '}'

    Add-FirstBootPowerShellScript -MountPath $MountPath -ScriptContent $psContent -ScriptName "WinGetInstall.ps1"
    Write-Log -msg "WinGet install script added for: $($Apps -join ', ')"
}

function Add-OfflineAppInstallers {
    <#
    .SYNOPSIS
        Downloads selected WinGet app installers at build time and bakes them into the
        image so they install on first boot WITHOUT requiring internet.
    .DESCRIPTION
        Uses 'winget download' on the build machine to fetch each app's installer (+ any
        dependencies) into a staging folder, copies them into the mounted image at
        C:\WID_Apps\<AppId>\, and writes an offline installer script (OfflineAppInstall.ps1)
        that is launched on first logon via RunOnce. The script detects each installer type
        (.exe/.msi/.msix/.appx) and installs it silently from the local copy.
        Falls back to online 'winget install' only if a local installer is missing.
    .PARAMETER MountPath
        Path to the mounted Windows image.
    .PARAMETER Apps
        Array of WinGet app IDs to download and stage.
    .PARAMETER StagingRoot
        Optional temp folder for downloads (defaults to WIDTemp\appstaging).
    #>
    param(
        [Parameter(Mandatory=$true)][string]$MountPath,
        [string[]]$Apps = @(),
        [string]$StagingRoot = ""
    )

    if ($Apps.Count -eq 0) { return }

    # Check winget is available on the build machine
    $wingetCmd = Get-Command winget -ErrorAction SilentlyContinue
    if (-not $wingetCmd) {
        Write-Host "  [WARN] winget not found on build machine - falling back to online install" -ForegroundColor Yellow
        Write-Log -msg "winget not available; using online WinGet install fallback"
        Add-WinGetInstallScript -MountPath $MountPath -Apps $Apps
        return
    }

    Write-Host "`n[INFO] Downloading $($Apps.Count) app installer(s) for offline install..." -ForegroundColor Cyan
    Write-Log -msg "Downloading offline app installers: $($Apps -join ', ')"

    if (-not $StagingRoot) { $StagingRoot = "$env:SystemDrive\WIDTemp\appstaging" }
    if (Test-Path $StagingRoot) { Remove-Item $StagingRoot -Recurse -Force -ErrorAction SilentlyContinue }
    New-Item -ItemType Directory -Path $StagingRoot -Force | Out-Null

    # Image destination for the baked-in installers
    $imageAppsDir = Join-Path $MountPath "WID_Apps"
    if (-not (Test-Path $imageAppsDir)) { New-Item -ItemType Directory -Path $imageAppsDir -Force | Out-Null }

    $downloaded = @()
    $failed = @()

    foreach ($appId in $Apps) {
        $safeId = ($appId -replace '[^\w\.\-]', '_')
        $appStage = Join-Path $StagingRoot $safeId
        New-Item -ItemType Directory -Path $appStage -Force | Out-Null

        Write-Host "  Downloading $appId..." -ForegroundColor DarkGray
        Write-Log -msg "winget download $appId"

        # winget download: machine scope, accept agreements, skip license (avoids EntraID auth)
        $args = @("download","--id",$appId,"--exact",
                  "--download-directory","`"$appStage`"",
                  "--accept-package-agreements","--accept-source-agreements",
                  "--skip-license","--disable-interactivity")
        try {
            $out = & winget @args 2>&1 | Out-String
            $out | Write-Log
            $files = Get-ChildItem -Path $appStage -Recurse -File -ErrorAction SilentlyContinue |
                     Where-Object { $_.Extension -in '.exe','.msi','.msix','.appx','.msixbundle','.appxbundle' }
            if ($files) {
                # Copy the staged installer files into the image
                $imageAppDir = Join-Path $imageAppsDir $safeId
                New-Item -ItemType Directory -Path $imageAppDir -Force | Out-Null
                Copy-Item -Path (Join-Path $appStage '*') -Destination $imageAppDir -Recurse -Force
                $downloaded += $safeId
                Write-Host "    [OK] $appId staged ($($files.Count) file(s))" -ForegroundColor Green
                Write-Log -msg "Staged offline installer for $appId ($($files.Count) files)"
            } else {
                $failed += $appId
                Write-Host "    [WARN] No installer downloaded for $appId (will install online)" -ForegroundColor Yellow
                Write-Log -msg "No installer file produced for $appId"
            }
        }
        catch {
            $failed += $appId
            Write-Host "    [WARN] Download failed for $appId (will install online)" -ForegroundColor Yellow
            Write-Log -msg "winget download failed for $appId`: $($_.Exception.Message)"
        }
    }

    # Build the first-boot offline installer script
    $ps = @()
    $ps += "# Offline App Installer - generated by Windows ISO Debloater"
    $ps += "# Installs apps from baked-in local installers (no internet required)."
    $ps += '$ErrorActionPreference = "SilentlyContinue"'
    $ps += '$root = "C:\WID_Apps"'
    $ps += '$log = "C:\WID_Apps\install.log"'
    $ps += 'function Log($m) { "$(Get-Date -Format o) $m" | Out-File $log -Append -Encoding utf8 }'
    $ps += 'Log "Offline app install started"'
    $ps += ''
    $ps += '# Locally staged apps (installed from baked-in files, no internet needed)'
    $ps += '$localApps = @('
    foreach ($d in $downloaded) { $ps += "    `"$d`"," }
    $ps += ')'
    $ps += ''
    $ps += '# Apps that could not be pre-downloaded (online winget fallback)'
    $ps += '$onlineApps = @('
    foreach ($f in $failed) { $ps += "    `"$f`"," }
    $ps += ')'
    $ps += ''
    $ps += 'foreach ($app in $localApps) {'
    $ps += '    $dir = Join-Path $root $app'
    $ps += '    if (-not (Test-Path $dir)) { Log "Missing dir: $dir"; continue }'
    $ps += '    Log "Installing $app from local files"'
    $ps += '    # Prefer winget local manifest/install if a .yaml manifest was produced'
    $ps += '    $yaml = Get-ChildItem $dir -Filter *.yaml -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1'
    $ps += '    $installed = $false'
    $ps += '    if ($yaml) {'
    $ps += '        try {'
    $ps += '            winget install --manifest $yaml.DirectoryName --accept-package-agreements --accept-source-agreements --silent --disable-interactivity'
    $ps += '            if ($LASTEXITCODE -eq 0) { $installed = $true; Log "$app installed via local manifest" }'
    $ps += '        } catch { Log "manifest install failed for $app : $_" }'
    $ps += '    }'
    $ps += '    if (-not $installed) {'
    $ps += '        # Install the raw installer file directly'
    $ps += '        $inst = Get-ChildItem $dir -Recurse -Include *.exe,*.msi,*.msix,*.appx,*.msixbundle,*.appxbundle -ErrorAction SilentlyContinue | Select-Object -First 1'
    $ps += '        if ($inst) {'
    $ps += '            Log "Running installer: $($inst.FullName)"'
    $ps += '            switch ($inst.Extension.ToLower()) {'
    $ps += '                ".msi" { Start-Process msiexec.exe -ArgumentList "/i `"$($inst.FullName)`" /qn /norestart" -Wait }'
    $ps += '                ".exe" { Start-Process $inst.FullName -ArgumentList "/S /silent /quiet /qn" -Wait }'
    $ps += '                default {'
    $ps += '                    try { Add-AppxPackage -Path $inst.FullName } catch { Log "Appx install failed: $_" }'
    $ps += '                }'
    $ps += '            }'
    $ps += '            Log "$app install attempted"'
    $ps += '        } else { Log "No installer file found for $app" }'
    $ps += '    }'
    $ps += '}'
    $ps += ''
    $ps += '# Online fallback for apps that failed to pre-download'
    $ps += 'if ($onlineApps.Count -gt 0) {'
    $ps += '    $tries = 0'
    $ps += '    while (-not (Test-Connection 8.8.8.8 -Count 1 -Quiet) -and $tries -lt 30) { Start-Sleep 10; $tries++ }'
    $ps += '    foreach ($app in $onlineApps) {'
    $ps += '        Log "Online install: $app"'
    $ps += '        winget install --id $app --exact --accept-package-agreements --accept-source-agreements --silent --disable-interactivity'
    $ps += '    }'
    $ps += '}'
    $ps += ''
    $ps += 'Log "Offline app install finished"'
    $ps += '# Clean up the baked-in installers to reclaim disk space'
    $ps += 'Remove-Item "C:\WID_Apps" -Recurse -Force -ErrorAction SilentlyContinue'

    Add-FirstBootPowerShellScript -MountPath $MountPath -ScriptContent $ps -ScriptName "OfflineAppInstall.ps1"

    $totalSize = 0
    if (Test-Path $imageAppsDir) {
        $totalSize = (Get-ChildItem $imageAppsDir -Recurse -File -ErrorAction SilentlyContinue | Measure-Object Length -Sum).Sum
    }
    $sizeMB = [math]::Round($totalSize / 1MB, 1)
    Write-Host "[OK] Baked in $($downloaded.Count) app(s) offline ($sizeMB MB). Online fallback for $($failed.Count)." -ForegroundColor Green
    Write-Log -msg "Offline app staging complete: $($downloaded.Count) local, $($failed.Count) online fallback, ${sizeMB}MB"

    # Clean up build-machine staging
    Remove-Item $StagingRoot -Recurse -Force -ErrorAction SilentlyContinue
}
